# Generated by Django 4.2.1 on 2025-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticaldata',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
    ]
