# Generated by Django 4.2.1 on 2025-05-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_statisticaldata_chart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldata',
            name='plotly_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
