# Generated by Django 4.2.1 on 2025-06-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_statisticaldata_plotly_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticaldata',
            name='plotly_json',
        ),
    ]
