# Generated by Django 4.2.1 on 2025-06-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_statisticaldata_plotly_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.TextField(default='Студент: Тренихин Михаил Александрович | Группа: РИ-231003 | Курс: Технологии программирования'),
        ),
    ]
