# Generated by Django 4.2.1 on 2025-06-21 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_siteconfiguration_footer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticaldata',
            name='chart_image',
            field=models.ImageField(blank=True, help_text='Upload chart as PNG, JPG, or SVG file', null=True, upload_to='charts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='vacancydata',
            name='key_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
